language: node_js
os: linux
dist: trusty
node_js:
  - '8'
notifications:
  email:
    recipients:
      - sebastien.jourdain@kitware.com
    on_success: change
    on_failure: always

cache:
  directories:
    - node_modules
    - Documentation/build-tmp

script:
  - npm install
  - git config --global user.name "Travis CI"
  - git config --global user.email "sebastien.jourdain@kitware.com"
  - export GIT_PUBLISH_URL=https://${GH_TOKEN}@github.com/Kitware/vtk-js-datasets.git
  - if [ "$TRAVIS_BRANCH" == "master" ]; then npm run doc:publish; fi
